<#
.SYNOPSIS
  SuperChat — one-command deploy for Windows (Docker Desktop).

.EXAMPLE
  .\deploy.ps1                       # localhost
  .\deploy.ps1 -PublicHost 10.0.0.50 # reachable from other machines on the LAN

  It verifies Docker, generates strong secrets in .env (first run only),
  renders the Keycloak realm, creates the rabbitmq_data volume, and starts the stack.
#>
[CmdletBinding()]
param([string]$PublicHost = "localhost")

$ErrorActionPreference = "Stop"
Set-Location -Path $PSScriptRoot

function Log($m){ Write-Host "==> $m" -ForegroundColor Cyan }
function Ok ($m){ Write-Host "OK  $m" -ForegroundColor Green }
function Die($m){ Write-Host "x   $m" -ForegroundColor Red; exit 1 }

# ── 1. Docker present? ────────────────────────────────────────────────────────
try { docker version --format '{{.Server.Version}}' | Out-Null }
catch { Die "Docker Desktop is not running or not installed. See DEPLOY.md -> 'Install Docker'." }
try { docker compose version | Out-Null } catch { Die "Docker Compose v2 is missing. Update Docker Desktop." }
Ok "Docker is ready."

# ── 2. Secrets (.env) — generated once, never overwritten ─────────────────────
function New-HexKey {
  $bytes = New-Object byte[] 32
  [System.Security.Cryptography.RandomNumberGenerator]::Create().GetBytes($bytes)
  -join ($bytes | ForEach-Object { $_.ToString('x2') })
}
if (-not (Test-Path .env)) {
  Log "Generating .env with strong secrets (first run only)..."
  $lines = @(
    "# Auto-generated by deploy.ps1 - keep this file private, do NOT commit it.",
    "AES_ENCRYPTION_KEY=$(New-HexKey)",
    "INTERNAL_API_TOKEN=$(New-HexKey)"
  )
  if ($PublicHost -ne "localhost") { $lines += "PUBLIC_HOST=$PublicHost" }
  Set-Content -Path .env -Value $lines -Encoding ascii
  Ok ".env created."
} else {
  Ok ".env already exists - leaving secrets untouched."
  if ($PublicHost -eq "localhost") {
    $existing = Select-String -Path .env -Pattern '^PUBLIC_HOST=(.+)$' | Select-Object -First 1
    if ($existing) { $PublicHost = $existing.Matches[0].Groups[1].Value }
  }
}

# ── 3. Render Keycloak realm ──────────────────────────────────────────────────
Log "Rendering Keycloak realm for host '$PublicHost'..."
$tpl = Get-Content keycloak/superchat-realm.template.json -Raw
$tpl = $tpl.Replace('${PUBLIC_HOST}', $PublicHost).Replace('${PUBLIC_DOMAIN}', $PublicHost)
Set-Content -Path keycloak/superchat-realm.json -Value $tpl -Encoding utf8
Ok "Realm rendered."

# ── 4. External RabbitMQ volume (idempotent) ─────────────────────────────────
docker volume create rabbitmq_data | Out-Null
Ok "Volume rabbitmq_data ready."

# ── 5. Build + start ──────────────────────────────────────────────────────────
Log "Building images and starting the stack (first run can take several minutes)..."
docker compose up -d --build

Write-Host ""
Ok "Stack is starting. Keycloak needs ~90-120s on first boot."
Write-Host "Frontend:    http://${PublicHost}:3000" -ForegroundColor Cyan
Write-Host "Admin panel: http://${PublicHost}:3002" -ForegroundColor Cyan
Write-Host "Keycloak:    http://${PublicHost}:8080  (admin / admin)" -ForegroundColor Cyan
Write-Host "Grafana:     http://${PublicHost}:3001  (admin / admin)" -ForegroundColor Cyan
Write-Host ""
Write-Host "Next: create users in Keycloak (realm 'superchat'). See DEPLOY.md -> 'First login'."
Write-Host "Watch progress:  docker compose ps   |   docker compose logs -f keycloak"
