#!/usr/bin/env bash
# SuperChat — one-command deploy for Linux / macOS (any distro with Docker installed).
#
#   ./deploy.sh                      # localhost
#   ./deploy.sh --host 10.0.0.50     # reachable from other machines on the LAN
#   PUBLIC_HOST=10.0.0.50 ./deploy.sh
#
# It will: verify Docker, generate strong secrets in .env (first run only),
# render the Keycloak realm, create the rabbitmq_data volume, and start the stack.
set -euo pipefail
cd "$(dirname "$0")"

c_g="\033[0;32m"; c_y="\033[0;33m"; c_c="\033[0;36m"; c_r="\033[0;31m"; c_0="\033[0m"
log(){ echo -e "${c_c}==>${c_0} $*"; }; ok(){ echo -e "${c_g}OK${c_0}  $*"; }
warn(){ echo -e "${c_y}!${c_0}  $*"; }; die(){ echo -e "${c_r}x${c_0}  $*" >&2; exit 1; }

# ── args ──────────────────────────────────────────────────────────────────────
PUBLIC_HOST="${PUBLIC_HOST:-localhost}"
while [[ $# -gt 0 ]]; do
  case "$1" in
    --host) PUBLIC_HOST="$2"; shift 2;;
    *) die "Unknown argument: $1 (use --host <ip-or-hostname>)";;
  esac
done

# ── 1. Docker present? ────────────────────────────────────────────────────────
command -v docker >/dev/null 2>&1 || die "Docker is not installed. See DEPLOY.md → 'Install Docker'."
docker compose version >/dev/null 2>&1 || die "Docker Compose v2 missing. Update Docker, or see DEPLOY.md."
docker info >/dev/null 2>&1 || die "Docker daemon not running / no permission. Start Docker (or add your user to the 'docker' group)."
ok "Docker $(docker version -f '{{.Server.Version}}' 2>/dev/null) ready."

# ── 2. Secrets (.env) — generated once, never overwritten ─────────────────────
gen_key(){ openssl rand -hex 32 2>/dev/null || head -c32 /dev/urandom | od -An -tx1 | tr -d ' \n'; }
if [[ ! -f .env ]]; then
  log "Generating .env with strong secrets (first run only)…"
  {
    echo "# Auto-generated by deploy.sh — keep this file private, do NOT commit it."
    echo "AES_ENCRYPTION_KEY=$(gen_key)"
    echo "INTERNAL_API_TOKEN=$(gen_key)"
    [[ "$PUBLIC_HOST" != "localhost" ]] && echo "PUBLIC_HOST=$PUBLIC_HOST"
  } > .env
  ok ".env created."
else
  ok ".env already exists — leaving secrets untouched."
  # honor an existing PUBLIC_HOST in .env if --host wasn't passed
  if grep -q '^PUBLIC_HOST=' .env && [[ "$PUBLIC_HOST" == "localhost" ]]; then
    PUBLIC_HOST="$(grep '^PUBLIC_HOST=' .env | head -1 | cut -d= -f2-)"
  fi
fi

# ── 3. Render Keycloak realm (no gettext dependency — pure sed) ───────────────
log "Rendering Keycloak realm for host '${PUBLIC_HOST}'…"
sed -e "s|\${PUBLIC_HOST}|${PUBLIC_HOST}|g" \
    -e "s|\${PUBLIC_DOMAIN}|${PUBLIC_HOST}|g" \
    keycloak/superchat-realm.template.json > keycloak/superchat-realm.json
ok "Realm rendered."

# ── 4. External RabbitMQ volume (idempotent) ─────────────────────────────────
docker volume create rabbitmq_data >/dev/null
ok "Volume rabbitmq_data ready."

# ── 5. Build + start ──────────────────────────────────────────────────────────
log "Building images and starting the stack (first run can take several minutes)…"
docker compose up -d --build

echo
ok "Stack is starting. Keycloak needs ~90–120s on first boot."
echo -e "${c_c}Frontend:${c_0}    http://${PUBLIC_HOST}:3000"
echo -e "${c_c}Admin panel:${c_0} http://${PUBLIC_HOST}:3002"
echo -e "${c_c}Keycloak:${c_0}    http://${PUBLIC_HOST}:8080  (admin / admin)"
echo -e "${c_c}Grafana:${c_0}     http://${PUBLIC_HOST}:3001  (admin / admin)"
echo
echo "Next: create users in Keycloak (realm 'superchat'). See DEPLOY.md → 'First login'."
echo "Watch progress:  docker compose ps   |   docker compose logs -f keycloak"
