global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:8090']
    metrics_path: /actuator/prometheus

  - job_name: 'chat-service'
    static_configs:
      - targets: ['chat-service:8082']
    metrics_path: /actuator/prometheus

  - job_name: 'user-service'
    static_configs:
      - targets: ['user-service:8083']
    metrics_path: /actuator/prometheus

  - job_name: 'notification-service'
    static_configs:
      - targets: ['notification-service:8084']
    metrics_path: /actuator/prometheus

  - job_name: 'worker-service'
    static_configs:
      - targets: ['worker-service:8085']
    metrics_path: /actuator/prometheus

  - job_name: 'admin-service'
    static_configs:
      - targets: ['admin-service:8086']
    metrics_path: /actuator/prometheus

  - job_name: 'moderation-service'
    static_configs:
      - targets: ['moderation-service:8087']
    metrics_path: /actuator/prometheus

  - job_name: 'compliance-service'
    static_configs:
      - targets: ['compliance-service:8088']
    metrics_path: /actuator/prometheus
